# Generated by Django 5.2.8 on 2025-11-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_department_alter_employee_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='basic_salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=15),
            preserve_default=False,
        ),
    ]
